apiVersion: apps/v1
kind: Deployment
metadata:
  name: links-deployment
  labels:
    app: q1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: q1
  template:
    metadata:
      labels:
        app: q1
    spec:
      containers:
      - name: links-container
        image: manasapeddi/linksapp:latest
        ports:
        - containerPort: 80
